### ISSUE TITLE
link: Add tcx support

### ISSUE THREAD

**Issue by borkmann** [cilium/ebpf#1117]
BPF link support for tcx [got merged](https://lore.kernel.org/all/20230719140858.13224-1-daniel@iogearbox.net/) recently. Add full tcx support for cilium/ebpf, so that we can utilise it in Cilium.

For the library, it would be good to have both, the link and opts variants similar as libbpf supports it.

Depending on available cycles, I'll take a look at this.
```[tasklist]
### Tasks
- [x] Add kernel >= 6.6 to CI
- [x] Auto generate syscall definitions for generic multi attach
- [x] Add txc link type (probably following XDP example)
```

**Comment by lmb** [comment]
Nice! Once tcx support is in we can also look at a fall back for netlink.

**Comment by lmb** [comment]
Relevant commit is https://github.com/torvalds/linux/commit/e420bed025071a623d2720a92bc2245c84757ecb

**Comment by borkmann** [comment]
> Relevant commit is [torvalds/linux@e420bed](https://github.com/torvalds/linux/commit/e420bed025071a623d2720a92bc2245c84757ecb)

This one too for the bpf_mprog API / control directives: https://github.com/torvalds/linux/commit/053c8e1f235dc3f69d13375b32f4209228e1cb96

**Comment by lmb** [comment]
Current WIP is at https://github.com/lmb/ebpf/tree/link-tcx

**Comment by lmb** [comment]
Done in https://github.com/cilium/ebpf/commit/417f8a264d2e691649ede9b995fb334e6c58ca71
